/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.wi.director.thrift.v1.metadata;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (1.0.0-dev)")
public class Range implements org.apache.thrift.TBase<Range, Range._Fields>, java.io.Serializable, Cloneable, Comparable<Range> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Range");

  private static final org.apache.thrift.protocol.TField RANGE_START_FIELD_DESC = new org.apache.thrift.protocol.TField("range_start", org.apache.thrift.protocol.TType.DOUBLE, (short)1);
  private static final org.apache.thrift.protocol.TField RANGE_END_FIELD_DESC = new org.apache.thrift.protocol.TField("range_end", org.apache.thrift.protocol.TType.DOUBLE, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RangeStandardSchemeFactory());
  }

  public double range_start; // optional
  public double range_end; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RANGE_START((short)1, "range_start"),
    RANGE_END((short)2, "range_end");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RANGE_START
          return RANGE_START;
        case 2: // RANGE_END
          return RANGE_END;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RANGE_START_ISSET_ID = 0;
  private static final int __RANGE_END_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.RANGE_START,_Fields.RANGE_END};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RANGE_START, new org.apache.thrift.meta_data.FieldMetaData("range_start", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.RANGE_END, new org.apache.thrift.meta_data.FieldMetaData("range_end", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Range.class, metaDataMap);
  }

  public Range() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Range(Range other) {
    __isset_bitfield = other.__isset_bitfield;
    this.range_start = other.range_start;
    this.range_end = other.range_end;
  }

  public Range deepCopy() {
    return new Range(this);
  }

  @Override
  public void clear() {
    setRange_startIsSet(false);
    this.range_start = 0.0;
    setRange_endIsSet(false);
    this.range_end = 0.0;
  }

  public double getRange_start() {
    return this.range_start;
  }

  public Range setRange_start(double range_start) {
    this.range_start = range_start;
    setRange_startIsSet(true);
    return this;
  }

  public void unsetRange_start() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __RANGE_START_ISSET_ID);
  }

  /** Returns true if field range_start is set (has been assigned a value) and false otherwise */
  public boolean isSetRange_start() {
    return EncodingUtils.testBit(__isset_bitfield, __RANGE_START_ISSET_ID);
  }

  public void setRange_startIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __RANGE_START_ISSET_ID, value);
  }

  public double getRange_end() {
    return this.range_end;
  }

  public Range setRange_end(double range_end) {
    this.range_end = range_end;
    setRange_endIsSet(true);
    return this;
  }

  public void unsetRange_end() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __RANGE_END_ISSET_ID);
  }

  /** Returns true if field range_end is set (has been assigned a value) and false otherwise */
  public boolean isSetRange_end() {
    return EncodingUtils.testBit(__isset_bitfield, __RANGE_END_ISSET_ID);
  }

  public void setRange_endIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __RANGE_END_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RANGE_START:
      if (value == null) {
        unsetRange_start();
      } else {
        setRange_start((Double)value);
      }
      break;

    case RANGE_END:
      if (value == null) {
        unsetRange_end();
      } else {
        setRange_end((Double)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RANGE_START:
      return getRange_start();

    case RANGE_END:
      return getRange_end();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RANGE_START:
      return isSetRange_start();
    case RANGE_END:
      return isSetRange_end();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Range)
      return this.equals((Range)that);
    return false;
  }

  public boolean equals(Range that) {
    if (that == null)
      return false;

    boolean this_present_range_start = true && this.isSetRange_start();
    boolean that_present_range_start = true && that.isSetRange_start();
    if (this_present_range_start || that_present_range_start) {
      if (!(this_present_range_start && that_present_range_start))
        return false;
      if (this.range_start != that.range_start)
        return false;
    }

    boolean this_present_range_end = true && this.isSetRange_end();
    boolean that_present_range_end = true && that.isSetRange_end();
    if (this_present_range_end || that_present_range_end) {
      if (!(this_present_range_end && that_present_range_end))
        return false;
      if (this.range_end != that.range_end)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_range_start = true && (isSetRange_start());
    list.add(present_range_start);
    if (present_range_start)
      list.add(range_start);

    boolean present_range_end = true && (isSetRange_end());
    list.add(present_range_end);
    if (present_range_end)
      list.add(range_end);

    return list.hashCode();
  }

  @Override
  public int compareTo(Range other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetRange_start()).compareTo(other.isSetRange_start());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRange_start()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.range_start, other.range_start);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRange_end()).compareTo(other.isSetRange_end());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRange_end()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.range_end, other.range_end);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Range(");
    boolean first = true;

    if (isSetRange_start()) {
      sb.append("range_start:");
      sb.append(this.range_start);
      first = false;
    }
    if (isSetRange_end()) {
      if (!first) sb.append(", ");
      sb.append("range_end:");
      sb.append(this.range_end);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RangeStandardSchemeFactory implements SchemeFactory {
    public RangeStandardScheme getScheme() {
      return new RangeStandardScheme();
    }
  }

  private static class RangeStandardScheme extends StandardScheme<Range> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Range struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RANGE_START
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.range_start = iprot.readDouble();
              struct.setRange_startIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RANGE_END
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.range_end = iprot.readDouble();
              struct.setRange_endIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Range struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isSetRange_start()) {
        oprot.writeFieldBegin(RANGE_START_FIELD_DESC);
        oprot.writeDouble(struct.range_start);
        oprot.writeFieldEnd();
      }
      if (struct.isSetRange_end()) {
        oprot.writeFieldBegin(RANGE_END_FIELD_DESC);
        oprot.writeDouble(struct.range_end);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

}

