/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.wi.director.thrift.v1.datasheet;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class data_sheetConstants {

  /**
   * Active sets per team
   */
  public static final int MAX_DATA_SHEET_SETS = 50000;

  /**
   * NOHTML
   */
  public static final int TEST_MAX_DATA_SHEET_SETS = 500;

  /**
   * Active definitions per data sheet set
   */
  public static final int MAX_DATA_SHEET_DEFINITIONS = 10000;

  /**
   * NOHTML
   */
  public static final int TEST_MAX_DATA_SHEET_DEFINITIONS = 100;

  /**
   * Active sheets per team
   */
  public static final int MAX_DATA_SHEETS = 50000;

  /**
   * NOHTML
   */
  public static final int TEST_MAX_DATA_SHEETS = 500;

}
